[GLOBAL]
pants_version = "2.29.0a0"
backend_packages.add = [
  "pants.backend.build_files.fmt.black",
  "pants.backend.plugin_development",
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[python]
interpreter_constraints = ["==3.11.*"]
enable_resolves = true
pip_version = "latest"
default_resolve = "pants-2.29"

[python.resolves]
"pants-2.29" = "3rdparty/python/pants-2.29.lock"
pytest = "3rdparty/python/pytest.lock"
mypy = "3rdparty/python/mypy.lock"

[python-bootstrap]
search_path = ["<PYENV>"]

[python-infer]
unowned_dependency_behavior = "error"

[python-repos]
find_links = ["https://wheels.pantsbuild.org/simple"]

[pytest]
args = ["--no-header", "-vv"]
install_from_resolve = "pytest"
requirements = ["//3rdparty/python:pytest"]

[pex-cli]
version = "v2.57.0"
known_versions = [
  "v2.57.0|macos_arm64|82956c5fa92ee382a6eec4ea4be7a007eaef4fcfb52a166460e7d8244996aebd|4797155",
  "v2.57.0|macos_x86_64|82956c5fa92ee382a6eec4ea4be7a007eaef4fcfb52a166460e7d8244996aebd|4797155",
  "v2.57.0|linux_arm64|82956c5fa92ee382a6eec4ea4be7a007eaef4fcfb52a166460e7d8244996aebd|4797155",
  "v2.57.0|linux_x86_64|82956c5fa92ee382a6eec4ea4be7a007eaef4fcfb52a166460e7d8244996aebd|4797155",
]

[flake8]
config = "build-support/flake8/.flake8"
