[GLOBAL]
pants_version = "2.27.0"
backend_packages.add = [
  "pants.backend.build_files.fmt.black",
  "pants.backend.plugin_development",
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[python]
interpreter_constraints = ["==3.11.*"]
enable_resolves = true
pip_version = "latest"
default_resolve = "pants-2.27"

[python.resolves]
"pants-2.27" = "3rdparty/python/pants-2.27.lock"
pytest = "3rdparty/python/pytest.lock"
mypy = "3rdparty/python/mypy.lock"

[python-bootstrap]
search_path = ["<PYENV>"]

[python-infer]
unowned_dependency_behavior = "error"

[python-repos]
find_links = ["https://wheels.pantsbuild.org/simple"]

[pytest]
args = ["--no-header", "-vv"]
install_from_resolve = "pytest"
requirements = ["//3rdparty/python:pytest"]

[pex-cli]
version = "v2.45.2"
known_versions = [
  "v2.45.2|macos_arm64|570a3d5ca306a39aa3a180bd4cf3e2661b7c74b0579422b34659246daf122384|4833957",
  "v2.45.2|macos_x86_64|570a3d5ca306a39aa3a180bd4cf3e2661b7c74b0579422b34659246daf122384|4833957",
  "v2.45.2|linux_arm64|570a3d5ca306a39aa3a180bd4cf3e2661b7c74b0579422b34659246daf122384|4833957",
  "v2.45.2|linux_x86_64|570a3d5ca306a39aa3a180bd4cf3e2661b7c74b0579422b34659246daf122384|4833957",
]

[flake8]
config = "build-support/flake8/.flake8"
